### ISSUE TITLE
Update default viewport size to Defold's default viewport size

### ISSUE THREAD

**Issue by subsoap** [klaytonkowalski/library-defold-rendy#3]
![2024-09-02 20_08_46](https://github.com/user-attachments/assets/596c6d1e-a1fa-49ab-9690-b81efd119f4a)

this should be 960x640 so it's more fitting what people will get when they create a new Defold project

**Comment by whiteboxdev** [comment]
I agree, although I remain skeptical of Defold's decision to go with such a strange resolution, rather than a standard 16:9 resolution. Updated.
